version: '3'

services:
 minio1:
  image: minio/minio
  volumes:
   - dunro1:/export
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: password
  command: server http://minio{1...4}/export
 minio2:
  image: minio/minio
  volumes:
   - dunro2:/export
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: password
  command: server http://minio{1...4}/export
 minio3:
  image: minio/minio
  volumes:
   - dunro3:/export
  ports:
   - "9003:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: password
  command: server http://minio{1...4}/export
 minio4:
  image: minio/minio
  volumes:
   - dunro4:/export
  ports:
   - "9004:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: password
  command: server http://minio{1...4}/export


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  dunro1:
    driver_opts:
      type: none
      device: $PWD/d1
      o: bind
  dunro2:
    driver_opts:
      type: none
      device: $PWD/d2
      o: bind
  dunro3:
    driver_opts:
      type: none
      device: $PWD/d3
      o: bind
  dunro4:
    driver_opts:
      type: none
      device: $PWD/d4
      o: bind
  
